version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - lifecycle/automated
      - team/ops
      - component/ci

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    registries: '*'
    labels:
      - lifecycle/automated
      - team/ops
      - component/dependencies
