[project]
name = "transport"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "elasticsearch7",
  "elasticsearch8",
  "elasticsearch9",
  "orjson >=3.11.3,<4",
  "blake3 >=1.0.8,<2",
  "constants",
  "kubernetes >=34.1.0,<35",
]

[tool.uv.sources]
constants = { workspace = true }
