[project]
name = "elasticsearch9_proxy"
version = "1.0.0"
description = "Proxy wrapper for elasticsearch-py 9.x client"
dependencies = [
  "elasticsearch9>=9.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
