name: Lint YAML files

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '*.yaml'
      - '**/*.yml'
      - '*.yml'
      - .yamlignore
      - .yamllint
      - .gitignore

  push:
    branches:
      - master
    paths:
      - '**/*.yaml'
      - '*.yaml'
      - '**/*.yml'
      - '*.yml'
      - .yamlignore
      - .yamllint
      - .gitignore

jobs:
  yamllint:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup python 3.12
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.12'

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Run yamllint
        run: python3 -m yamllint --config-file=.yamllint.yaml --format=github .
